# 5/5/2019 5:56:00 PM
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at Server.Network.NetState.Dispose(Boolean flush) in C:\System\UO\UOServer\Server\Network\NetState.cs:line 1117


# 5/6/2019 12:03:09 AM
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at Server.Network.NetState.Flush() in C:\System\UO\UOServer\Server\Network\NetState.cs:line 1004


# 5/6/2019 3:50:04 AM
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at Server.Network.NetState.Dispose(Boolean flush) in C:\System\UO\UOServer\Server\Network\NetState.cs:line 1117


# 5/6/2019 7:04:50 AM
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at Server.Network.NetState.Flush() in C:\System\UO\UOServer\Server\Network\NetState.cs:line 1004


# 5/6/2019 11:56:33 PM
System.Net.Sockets.SocketException (0x80004005): An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at Server.Network.NetState.InternalBeginReceive() in C:\System\UO\UOServer\Server\Network\NetState.cs:line 804
   at Server.Network.NetState.Resume() in C:\System\UO\UOServer\Server\Network\NetState.cs:line 961


# 5/8/2019 2:41:09 PM
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at Server.Network.NetState.Flush() in C:\System\UO\UOServer\Server\Network\NetState.cs:line 1004


# 5/9/2019 4:12:20 PM
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at Server.Network.NetState.Dispose(Boolean flush) in C:\System\UO\UOServer\Server\Network\NetState.cs:line 1117


# 5/9/2019 4:12:20 PM
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at Server.Network.NetState.Dispose(Boolean flush) in C:\System\UO\UOServer\Server\Network\NetState.cs:line 1117


# 5/9/2019 4:12:20 PM
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at Server.Network.NetState.Dispose(Boolean flush) in C:\System\UO\UOServer\Server\Network\NetState.cs:line 1117


# 5/9/2019 4:29:09 PM
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at Server.Network.NetState.Dispose(Boolean flush) in C:\System\UO\UOServer\Server\Network\NetState.cs:line 1117


# 5/9/2019 4:29:09 PM
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at Server.Network.NetState.Dispose(Boolean flush) in C:\System\UO\UOServer\Server\Network\NetState.cs:line 1117


# 12/16/2019 4:00:55 PM
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at Server.Network.NetState.Flush() in C:\UO\UOServer\Server\Network\NetState.cs:line 1004


# 12/18/2019 9:31:10 PM
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at Server.Network.NetState.Flush() in C:\UO\UOServer\Server\Network\NetState.cs:line 1004


# 12/20/2019 5:54:53 AM
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at Server.Network.NetState.Flush() in C:\UO\UOServer\Server\Network\NetState.cs:line 1004


# 12/20/2019 6:00:52 PM
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at Server.Network.NetState.Flush() in C:\UO\UOServer\Server\Network\NetState.cs:line 1004


# 12/21/2019 7:03:35 AM
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at Server.Network.NetState.Flush() in C:\UO\UOServer\Server\Network\NetState.cs:line 1004


